export const productArray = [
    {
        name: "Boots-1",
        category: "boots",
        colour: ["dark brown", "black",],
        size: [
            "42", "43", "45", "48",
        ],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam imperdiet ullamcorper ex. Nunc ultrices arcu nec justo luctus, id dictum metus placerat.",
        author_1: "Adam",
        reviev_1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam imperdiet ullamcorper ex.",
        author_2: "Stian",
        reviev_2: "Etiam imperdiet ullamcorper ex.",
        image: "boots/boots-1.jpg",
        id: "1",
        price: 1699,
        new_in: 1,
        bestsellers: 0,
        outlet: 0,
        discount: "icons/discount.png",
    },
    {
        name: "Boots-2",
        category: "boots",
        colour: ["light brown", "blue",],
        size: [
            "42", "43", "47", "48",
        ],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam imperdiet ullamcorper ex. Nunc ultrices arcu nec justo luctus, id dictum metus placerat.",
        author_1: "Adam",
        reviev_1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam imperdiet ullamcorper ex.",
        author_2: "Stian",
        reviev_2: "Etiam imperdiet ullamcorper ex.",
        image: "boots/boots-2.jpg",
        id: "2",
        price: 1399,
        new_in: 0,
        bestsellers: 0,
        outlet: 0,
        discount: "icons/discount.png",
    },
    {
        name: "Boots-3",
        category: "boots",
        colour: ["light brown",],
        size: [
            "42", "45", "48",
        ],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam imperdiet ullamcorper ex. Nunc ultrices arcu nec justo luctus, id dictum metus placerat.",
        author_1: "Adam",
        reviev_1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam imperdiet ullamcorper ex.",
        author_2: "Stian",
        reviev_2: "Etiam imperdiet ullamcorper ex.",
        image: "boots/boots-3.jpg",
        id: "3",
        price: 2699,
        new_in: 0,
        bestsellers: 0,
        outlet: 0,
        discount: "icons/discount.png",
    },
    {
        name: "Boots-4",
        category: "boots",
        colour: ["dark brown", "black",],
        size: [
            "42", "43", "45", "46", "47", "48",
        ],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam imperdiet ullamcorper ex. Nunc ultrices arcu nec justo luctus, id dictum metus placerat.",
        author_1: "Adam",
        reviev_1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam imperdiet ullamcorper ex.",
        author_2: "Stian",
        reviev_2: "Etiam imperdiet ullamcorper ex.",
        image: "boots/boots-4.jpg",
        id: "4",
        price: 2199,
        new_in: 1,
        bestsellers: 1,
        outlet: 0,
        discount: "icons/discount.png",
    },
    {
        name: "Boots-5",
        category: "boots",
        colour: ["dark brown", "black",],
        size: [
            "42", "43", "45", "48",
        ],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam imperdiet ullamcorper ex. Nunc ultrices arcu nec justo luctus, id dictum metus placerat.",
        author_1: "Adam",
        reviev_1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam imperdiet ullamcorper ex.",
        author_2: "Stian",
        reviev_2: "Etiam imperdiet ullamcorper ex.",
        image: "boots/boots-5.jpg",
        id: "5",
        price: 2299,
        new_in: 0,
        bestsellers: 0,
        outlet: 0,
        discount: "icons/discount.png",
    },
    {
        name: "Boots-6",
        category: "boots",
        colour: ["dark brown", "black",],
        size: [
            "42", "43", "45", "48",
        ],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam imperdiet ullamcorper ex. Nunc ultrices arcu nec justo luctus, id dictum metus placerat.",
        author_1: "Adam",
        reviev_1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam imperdiet ullamcorper ex.",
        author_2: "Stian",
        reviev_2: "Etiam imperdiet ullamcorper ex.",
        image: "boots/boots-6.jpg",
        id: "6",
        price: 3099,
        new_in: 0,
        bestsellers: 0,
        outlet: 0,
        discount: "icons/discount.png",
    },
    {
        name: "Boots-7",
        category: "boots",
        colour: ["dark brown", "black",],
        size: [
            "42", "43", "45", "48",
        ],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam imperdiet ullamcorper ex. Nunc ultrices arcu nec justo luctus, id dictum metus placerat.",
        author_1: "Adam",
        reviev_1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam imperdiet ullamcorper ex.",
        author_2: "Stian",
        reviev_2: "Etiam imperdiet ullamcorper ex.",
        image: "boots/boots-7.jpg",
        id: "7",
        price: 3099,
        new_in: 0,
        bestsellers: 0,
        outlet: 1,
        discount: "icons/discount.png",
    },
    {
        name: "Boots-8",
        category: "boots",
        colour: ["light brown", "blue",],
        size: [
            "42", "43", "45", "48",
        ],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam imperdiet ullamcorper ex. Nunc ultrices arcu nec justo luctus, id dictum metus placerat.",
        author_1: "Adam",
        reviev_1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam imperdiet ullamcorper ex.",
        author_2: "Stian",
        reviev_2: "Etiam imperdiet ullamcorper ex.",
        image: "boots/boots-8.jpg",
        id: "8",
        price: 1699,
        new_in: 0,
        bestsellers: 0,
        outlet: 0,
        discount: "icons/discount.png",
    },
    {
        name: "Lace_up-1",
        category: "lace_up",
        colour: ["light brown", "blue",],
        size: [
            "42", "43", "45", "48",
        ],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam imperdiet ullamcorper ex. Nunc ultrices arcu nec justo luctus, id dictum metus placerat.",
        author_1: "Adam",
        reviev_1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam imperdiet ullamcorper ex.",
        author_2: "Stian",
        reviev_2: "Etiam imperdiet ullamcorper ex.",
        image: "lace_up/lace_up-1.jpg",
        id: "9",
        price: 1999,
        new_in: 0,
        bestsellers: 1,
        outlet: 0,
        discount: "icons/discount.png",
    },
    {
        name: "Lace_up-2",
        category: "lace_up",
        colour: ["light brown",],
        size: [
            "42", "43", "45", "48",
        ],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam imperdiet ullamcorper ex. Nunc ultrices arcu nec justo luctus, id dictum metus placerat.",
        author_1: "Adam",
        reviev_1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam imperdiet ullamcorper ex.",
        author_2: "Stian",
        reviev_2: "Etiam imperdiet ullamcorper ex.",
        image: "lace_up/lace_up-2.jpg",
        id: "10",
        price: 2099,
        new_in: 0,
        bestsellers: 0,
        outlet: 0,
        discount: "icons/discount.png",
    },
    {
        name: "Lace_up-3",
        category: "lace_up",
        colour: ["dark brown", "black",],
        size: [
            "42", "43", "45", "48",
        ],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam imperdiet ullamcorper ex. Nunc ultrices arcu nec justo luctus, id dictum metus placerat.",
        author_1: "Adam",
        reviev_1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam imperdiet ullamcorper ex.",
        author_2: "Stian",
        reviev_2: "Etiam imperdiet ullamcorper ex.",
        image: "lace_up/lace_up-3.jpg",
        id: "11",
        price: 1699,
        new_in: 0,
        bestsellers: 0,
        outlet: 0,
        discount: "icons/discount.png",
    },
    {
        name: "Sandals-1",
        category: "sandals",
        colour: ["dark brown", "black",],
        size: [
            "42", "43", "45", "48",
        ],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam imperdiet ullamcorper ex. Nunc ultrices arcu nec justo luctus, id dictum metus placerat.",
        author_1: "Adam",
        reviev_1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam imperdiet ullamcorper ex.",
        author_2: "Stian",
        reviev_2: "Etiam imperdiet ullamcorper ex.",
        image: "sandals/sandals-1.jpg",
        id: "12",
        price: 1399,
        new_in: 0,
        bestsellers: 0,
        outlet: 1,
        discount: "icons/discount.png",
    },
    {
        name: "Sandals-2",
        category: "sandals",
        colour: ["dark brown", "black",],
        size: [
            "42", "43", "45", "48",
        ],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam imperdiet ullamcorper ex. Nunc ultrices arcu nec justo luctus, id dictum metus placerat.",
        author_1: "Adam",
        reviev_1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam imperdiet ullamcorper ex.",
        author_2: "Stian",
        reviev_2: "Etiam imperdiet ullamcorper ex.",
        image: "sandals/sandals-2.jpg",
        id: "13",
        price: 2099,
        new_in: 1,
        bestsellers: 0,
        outlet: 0,
        discount: "icons/discount.png",
    },
    {
        name: "Sandals-3",
        category: "sandals",
        colour: ["light brown", "blue",],
        size: [
            "42", "43", "45", "48",
        ],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam imperdiet ullamcorper ex. Nunc ultrices arcu nec justo luctus, id dictum metus placerat.",
        author_1: "Adam",
        reviev_1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam imperdiet ullamcorper ex.",
        author_2: "Stian",
        reviev_2: "Etiam imperdiet ullamcorper ex.",
        image: "sandals/sandals-3.jpg",
        id: "14",
        price: 1699,
        new_in: 0,
        bestsellers: 0,
        outlet: 0,
        discount: "icons/discount.png",
    },
    {
        name: "Slip_on-1",
        category: "slip_on",
        colour: ["light brown", "blue",],
        size: [
            "42", "43", "45", "48",
        ],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam imperdiet ullamcorper ex. Nunc ultrices arcu nec justo luctus, id dictum metus placerat.",
        author_1: "Adam",
        reviev_1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam imperdiet ullamcorper ex.",
        author_2: "Stian",
        reviev_2: "Etiam imperdiet ullamcorper ex.",
        image: "slip_on/slip_on-1.jpg",
        id: "15",
        price: 2099,
        new_in: 0,
        bestsellers: 0,
        outlet: 0,
        discount: "icons/discount.png",
    },
    {
        name: "Slip_on-2",
        category: "slip_on",
        colour: ["light brown", "blue",],
        size: [
            "42", "43", "45", "48",
        ],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam imperdiet ullamcorper ex. Nunc ultrices arcu nec justo luctus, id dictum metus placerat.",
        author_1: "Adam",
        reviev_1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam imperdiet ullamcorper ex.",
        author_2: "Stian",
        reviev_2: "Etiam imperdiet ullamcorper ex.",
        image: "slip_on/slip_on-2.jpg",
        id: "16",
        price: 1699,
        new_in: 0,
        bestsellers: 0,
        outlet: 0,
        discount: "icons/discount.png",
    },
    {
        name: "Slip_on-3",
        category: "slip_on",
        colour: ["dark brown", "black",],
        size: [
            "42", "43", "45", "48",
        ],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam imperdiet ullamcorper ex. Nunc ultrices arcu nec justo luctus, id dictum metus placerat.",
        author_1: "Adam",
        reviev_1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam imperdiet ullamcorper ex.",
        author_2: "Stian",
        reviev_2: "Etiam imperdiet ullamcorper ex.",
        image: "slip_on/slip_on-3.jpg",
        id: "17",
        price: 1399,
        new_in: 0,
        bestsellers: 0,
        outlet: 0,
        discount: "icons/discount.png",
    },
    {
        name: "Slip_on-4",
        category: "slip_on",
        colour: ["dark brown", "black",],
        size: [
            "42", "43", "45", "48",
        ],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam imperdiet ullamcorper ex. Nunc ultrices arcu nec justo luctus, id dictum metus placerat.",
        author_1: "Adam",
        reviev_1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam imperdiet ullamcorper ex.",
        author_2: "Stian",
        reviev_2: "Etiam imperdiet ullamcorper ex.",
        image: "slip_on/slip_on-4.jpg",
        id: "18",
        price: 2099,
        new_in: 0,
        bestsellers: 0,
        outlet: 0,
        discount: "icons/discount.png",
    },
    {
        name: "Slip_on-5",
        category: "slip_on",
        colour: ["light brown", "blue",],
        size: [
            "42", "43", "45", "48",
        ],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam imperdiet ullamcorper ex. Nunc ultrices arcu nec justo luctus, id dictum metus placerat.",
        author_1: "Adam",
        reviev_1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam imperdiet ullamcorper ex.",
        author_2: "Stian",
        reviev_2: "Etiam imperdiet ullamcorper ex.",
        image: "slip_on/slip_on-5.jpg",
        id: "19",
        price: 1699,
        new_in: 0,
        bestsellers: 0,
        outlet: 0,
        discount: "icons/discount.png",
    },
    {
        name: "Sneakers-1",
        category: "sneakers",
        colour: ["blue",],
        size: [
            "42", "43", "45", "48",
        ],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam imperdiet ullamcorper ex. Nunc ultrices arcu nec justo luctus, id dictum metus placerat.",
        author_1: "Adam",
        reviev_1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam imperdiet ullamcorper ex.",
        author_2: "Stian",
        reviev_2: "Etiam imperdiet ullamcorper ex.",
        image: "sneakers/sneakers-1.jpg",
        id: "20",
        price: 1799,
        new_in: 0,
        bestsellers: 0,
        outlet: 0,
        discount: "icons/discount.png",
    },
    {
        name: "Sneakers-2",
        category: "sneakers",
        colour: ["dark brown", "black",],
        size: [
            "42", "43", "45", "48",
        ],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam imperdiet ullamcorper ex. Nunc ultrices arcu nec justo luctus, id dictum metus placerat.",
        author_1: "Adam",
        reviev_1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam imperdiet ullamcorper ex.",
        author_2: "Stian",
        reviev_2: "Etiam imperdiet ullamcorper ex.",
        image: "sneakers/sneakers-2.jpg",
        id: "21",
        price: 2099,
        new_in: 0,
        bestsellers: 0,
        outlet: 0,
        discount: "icons/discount.png",
    },
    {
        name: "Sneakers-3",
        category: "sneakers",
        colour: ["dark brown", "black",],
        size: [
            "42", "43", "45", "48",
        ],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam imperdiet ullamcorper ex. Nunc ultrices arcu nec justo luctus, id dictum metus placerat.",
        author_1: "Adam",
        reviev_1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam imperdiet ullamcorper ex.",
        author_2: "Stian",
        reviev_2: "Etiam imperdiet ullamcorper ex.",
        image: "sneakers/sneakers-3.jpg",
        id: "22",
        price: 1699,
        new_in: 0,
        bestsellers: 1,
        outlet: 0,
        discount: "icons/discount.png",
    },
    {
        name: "Belt",
        category: "accessories",
        colour: ["dark brown", "black",],
        size: [
            "one size"
        ],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam imperdiet ullamcorper ex. Nunc ultrices arcu nec justo luctus, id dictum metus placerat.",
        author_1: "Adam",
        reviev_1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam imperdiet ullamcorper ex.",
        author_2: "Stian",
        reviev_2: "Etiam imperdiet ullamcorper ex.",
        image: "accessories/accessories-1.jpg",
        id: "23",
        price: 799,
        new_in: 0,
        bestsellers: 0,
        outlet: 0,
        discount: "icons/discount.png",
    },
    {
        name: "Brush",
        category: "accessories",
        colour: ["dark brown", "black",],
        size: [
            "one size"
        ],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam imperdiet ullamcorper ex. Nunc ultrices arcu nec justo luctus, id dictum metus placerat.",
        author_1: "Adam",
        reviev_1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam imperdiet ullamcorper ex.",
        author_2: "Stian",
        reviev_2: "Etiam imperdiet ullamcorper ex.",
        image: "accessories/accessories-2.jpg",
        id: "24",
        price: 599,
        new_in: 0,
        bestsellers: 0,
        outlet: 0,
        discount: "icons/discount.png",
    },
    {
        name: "Belt",
        category: "accessories",
        colour: ["dark brown", "black",],
        size: [
            "one size"
        ],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam imperdiet ullamcorper ex. Nunc ultrices arcu nec justo luctus, id dictum metus placerat.",
        author_1: "Adam",
        reviev_1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam imperdiet ullamcorper ex.",
        author_2: "Stian",
        reviev_2: "Etiam imperdiet ullamcorper ex.",
        image: "accessories/accessories-3.jpg",
        id: "25",
        price: 799,
        new_in: 0,
        bestsellers: 0,
        outlet: 0,
        discount: "icons/discount.png",
    },
    {
        name: "Brush",
        category: "accessories",
        colour: ["black",],
        size: [
            "one size"
        ],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam imperdiet ullamcorper ex. Nunc ultrices arcu nec justo luctus, id dictum metus placerat.",
        author_1: "Adam",
        reviev_1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam imperdiet ullamcorper ex.",
        author_2: "Stian",
        reviev_2: "Etiam imperdiet ullamcorper ex.",
        image: "accessories/accessories-4.jpg",
        id: "26",
        price: 499,
        new_in: 0,
        bestsellers: 0,
        outlet: 1,
        discount: "icons/discount.png",
    },
];